resources:
- name: repo
  type: git
  source:
    uri: https://github.com/crisksiq/concourse-ci-cypress-cucumber.git

jobs:
- name: e2e-automation-testing
  plan:
  - get: repo
    trigger: false   # tell Concourse to trigger this job when new versions are emitted
  - task: load-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cypress/browsers
          tags: node18.6.0-chrome105-ff104
      inputs: # add the get step as an input to this task
      - name: repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd repo/e2e-test
          npm install
          npm run headless
